--SQL Creation of FACT_SALESORDER

CREATE TABLE FACT_SALESORDER (
    SALESORDER_ID             NUMBER(10,0)     NULL,
    SALESORDERDETAIL_ID       NUMBER(10,0)     NOT NULL,
    REVISIONNUMBER            NUMBER(10,0)     NULL,
    ORDERDATE                 TIMESTAMP(9)     NULL,
    DUEDATE                   TIMESTAMP(9)     NULL,
    SHIPDATE                  TIMESTAMP(9)     NULL,
    STATUS                    NUMBER(10,0)     NULL,
    ONLINEORDERFLAG           NVARCHAR2(1 CHAR) NULL,
    SALESORDERNUMBER          NVARCHAR2(25 CHAR) NULL,
    PURCHASEORDERNUMBER       NVARCHAR2(25 CHAR) NULL,
    ACCOUNTNUMBER             NVARCHAR2(15 CHAR) NULL,
    CARRIERTRACKINGNUMBER     NVARCHAR2(25 CHAR) NULL,
    ORDERQTY                  NUMBER(10,0)     NULL,
    UNITPRICE                 NUMBER(19,4)     NULL,
    SPECIALOFFER_DISCOUNTPCT  NUMBER(10,4)     NULL,
    SPECIALOFFER_DESCRIPTION  NVARCHAR2(255 CHAR) NULL,
    LINETOTAL                 NUMBER(38,6)     NULL,
    TERRITORY_COUNTRYREGIONCODE NVARCHAR2(3 CHAR) NULL,
    FROM_CURRENCY_NAME        NVARCHAR2(50 CHAR) NULL,
    TO_CURRENCY_NAME          NVARCHAR2(50 CHAR) NULL,
    CURRENCYAVERAGERATE       NUMBER(19,4)     NULL,
    SUBTOTAL                  NUMBER(19,4)     NULL,
    TAXAMT                    NUMBER(19,4)     NULL,
    FREIGHT                   NUMBER(19,4)     NULL,
    TOTALDUE                  NUMBER(19,4)     NULL,
    "COMMENT"                   NVARCHAR2(128 CHAR) NULL,
    SALESPERSONNAME           NVARCHAR2(200 CHAR) NULL,
    CREDITCARDAPPROVALCODE    NVARCHAR2(15 CHAR) NULL,
    CARDTYPE                  NVARCHAR2(25 CHAR) NULL,
    CARDNUMBER                NVARCHAR2(25 CHAR) NULL,
    CUSTOMERID                NUMBER(10,0)     NULL,
    PRODUCTID                 NUMBER(10,0)     NULL,
    SNAPSHOT_DATE             DATE             NOT NULL,
);



--SQL Creation of DIM_PRODUCT


CREATE TABLE DIM_PRODUCT (
    SURROGATE_KEY        NUMBER           NOT NULL,
    PRODUCTID           NUMBER(10,0)     NOT NULL,
    PRODUCT_NAME        NVARCHAR2(50 CHAR) NULL,
    PRODUCTNUMBER       NVARCHAR2(25 CHAR) NULL,
    MAKEFLAG            NVARCHAR2(1 CHAR) NULL,
    FINISHEDGOODSFLAG   NVARCHAR2(1 CHAR) NULL,
    COLOR              NVARCHAR2(15 CHAR) NULL,
    SAFETYSTOCKLEVEL    NUMBER(10,0)     NULL,
    REORDERPOINT        NUMBER(10,0)     NULL,
    STANDARDCOST        NUMBER(19,4)     NULL,
    LISTPRICE          NUMBER(19,4)     NULL,
    "SIZE"               NVARCHAR2(5 CHAR) NULL,
    SELLSTARTDATE      TIMESTAMP(9)     NULL,
    SELLENDDATE        TIMESTAMP(9)     NULL,
    DISCONTINUEDDATE   TIMESTAMP(9)     NULL,
    START_DATE         DATE             NOT NULL,
    END_DATE           DATE             NOT NULL,
);


--SQL Creation of DIM_CUSTOMER


CREATE TABLE DIM_CUSTOMER (
    SURROGATE_KEY      NUMBER              NOT NULL,
    CUSTOMERID        NUMBER(10,0)        NULL,
    CUSTOMER_NAME     NVARCHAR2(150 CHAR) NULL,
    PHONENUMBER       NVARCHAR2(25 CHAR)  NULL,
    EMAILADDRESS      NVARCHAR2(50 CHAR)  NULL,
    ACCOUNTNUMBER     NVARCHAR2(10 CHAR)  NULL,
    STORE_NAME        NVARCHAR2(50 CHAR)  NULL,
    START_DATE        DATE                NULL,
    END_DATE          DATE                NULL,
);
